implementação da questão 18
estudos-db/Lilian-Carvalho pull request #16
Opened 2023-03-22 19:27 UTC by liliantavarez

2023-03-23 18:13 UTC, DRodrigues17 requested changes
deixei uns comentários nas classes, me chame qualquer coisa

2023-03-23 18:13 UTC, DRodrigues17 commented on 18-automoveis/src/main/java/com/example/automoveis/model/Automovel.java
aqui eu acredito que poderiam ser escolhidos uns nomes mais claros, quanto às variáveis freio e acelerador, algo tipo isFreioPressionado e isAceleradorPuxado. Quanto aos métodos, quem sabe no ligar mudar pra  variável receber true ou false ao invés de seu oposto, pois parando pra pensar, em um cenário em que o carro estivesse ligado e você chama o método ligar, a variável receberia false ( no método de ligar), revise isso nos métodos de freiar e acelerar também (mas antes troque os nomes das variáveis).

2023-03-23 18:13 UTC, DRodrigues17 commented on 18-automoveis/src/main/java/com/example/automoveis/model/Guincho.java
aqui segue a linha dos nomes mesmo, acho que o Set poderia ter um nome do tipo "veiculosCarregados", de resto tudo ok. Já aproveitando para abrir outro parêntese sobre as classes, seria bom por coisas nelas que as tornassem únicas, que fizesse a herança ter sentido, como por exemplo o freio ficar na classe de carro automático e acelerador na classe de moto com pedal, como fala no enunciado. Outra coisa que tu poderia cuidar é os métodos de get por exemplo, talvez não seja necessário, lembre-se do YAGNI!.

2023-03-23 18:13 UTC, DRodrigues17 commented on 18-automoveis/src/test/java/com/example/automoveis/model/CarroAutomaticoTest.java
aqui(classe CarroAutomatico e MotoPartidaPedal) os testes estão bons, mas acho que tu deveria checar aquilo que falei dos métodos, pra ficar um pouco mais seguro, pois como disse, quando tu chama o método 2 vezes o atributo volta ao estado "inicial", o que não deveria acontecer

2023-03-23 18:13 UTC, DRodrigues17 commented on 18-automoveis/src/test/java/com/example/automoveis/model/GuinchoTest.java
ok, eu tava vendo aqui, os testes es tão bons também, mas dá uma revisada no método de carregar, talvez ele n precise ser boolean, talvez o atributo carregado não precise receber seu oposto e sim um true, só uma dica

2023-03-24 01:17 UTC, liliantavarez commented on 18-automoveis/src/main/java/com/example/automoveis/model/Guincho.java
nome ajustado; os metados get estão sendo usados;

2023-03-24 13:32 UTC, DRodrigues17 approved these changes
é isso, excelente

2023-03-24 13:44 UTC, emanuelbispoc commented
Muito bom

2023-03-27 13:29 UTC, merged