implementação da questão 15
estudos-db/Lilian-Carvalho pull request #18
Opened 2023-03-24 01:13 UTC by liliantavarez

2023-03-24 18:06 UTC, DRodrigues17 requested changes
uma dica que já te dou de inicio é que, não julgo necessário criar um projeto novo pra cada exercício, acredito que uma pasta dentro da src pra cada um deles seja mais adequado.

2023-03-24 18:06 UTC, DRodrigues17 commented on 15-calculadora-static/src/main/java/com/example/calculadora/services/Calculadora.java
um comentário que poderia fazer qui sobre o método de potencia é que, talvez se ele tivesse 2 parâmetros seria mais adequado, pois nisso n dependeria da classe Math, fora que com o Math.pow, tu n tá fazendo potencia e sim o quadrado, nisso teria q ter outro pro cubo, quarta potencia, quinta, sexta....

2023-03-24 18:06 UTC, DRodrigues17 commented on 15-calculadora-static/src/test/java/com/example/calculadora/services/CalculadoraTest.java
aqui os testes estão bons dentro do que os métodos fazem. Só uma dica que gostaria de dar seria de não declarar uma variável com o valor esperado, talvez passar ele direto no assertEquals seja melhor, procure só usar essa prática quando o esperado depender de alguma instancia ou de alguma coisa mais complexa do que um valor fixo.

2023-03-27 13:20 UTC, liliantavarez commented on 15-calculadora-static/src/main/java/com/example/calculadora/services/Calculadora.java
O método da potencia possui dois parametros: double calcularPotencia(int base, int expoente). Que são justamente os valores usados pelo método pow para calcular o valor do primeiro parâmetro elevado ao segundo parâmetro. 

https://www.geeksforgeeks.org/math-pow-method-in-java-with-example/

2023-03-28 13:57 UTC, emanuelbispoc approved these changes

2023-03-28 16:36 UTC, merged